In [ ]:
from random import choice
from numpy import array, dot, random

In [ ]:
unit_step = lambda x: 0 if x < 0 else 1

In [ ]:
training_data = [
    (array([1,0,0]), 0),
    (array([1,0,1]), 0),
    (array([1,1,0]), 0),
    (array([1,1,1]), 1),
]

In [ ]:
w = 1 # bias =1

In [ ]:
errors = []
eta = 0.2
n = 100

In [ ]:
for i in xrange(n):
    x, expected = choice(training_data)
    result = dot(w, x)
    error = expected - unit_step(result)
    errors.append(error)
    w += eta * error * x

In [ ]:
for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))